### ISSUE TITLE
Can't set below 1970 Year as mindate

### ISSUE THREAD

**Issue by edvenkat** [alex-pl/cordova-plugin-datetimepicker#6]
Can't set below 1970 Year as mindate please advice 

var minDateAndroid = parseInt(d.getFullYear())-50 +"-" +("0"+(parseInt(d.getMonth())+1)).slice(-2)+"-"+("0"+(parseInt(d.getDate()))).slice(-2);

var options = {
	type: 'date',         // 'date' or 'time', required
	date: new Date(selectedDateAndroid),     // date or timestamp, default: current date
	minDate: new Date(minDateAndroid).getTime(),  // date or timestamp
	maxDate: new Date(maxDateAndroid).getTime()   // date or timestamp
};
				
window.DateTimePicker.pick(options, function (timestamp) {
})

**Comment by alex-pl** [comment]
Thank you for reporting this issue!
I was able to reproduce it and already found the problem, so there is no problem with your code.
A fix is in the making :).

**Comment by alex-pl** [comment]
New release 1.1.2 is available on npm.
